Cafe/Models/CafeProduct.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cafe.Models
{
    public class CafeProduct
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(50)]
        public string Description { get; set; }


        public int SizeId { get; set; }
        public Size Size { get; set; }

    }
}

Cafe/Controllers/CafeProductController.cs
using Cafe.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Cafe.Controllers
{
    [Authorize]
    public class CafeProductController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public CafeProductController(AppDbContext appDbContext)
        {
            
            _appDbContext = appDbContext;
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<CafeProduct> lista=_appDbContext.CafeProducts.Include(c=>c.Size).ToList();
            return View(lista);
        }


        [HttpGet]
        public IActionResult Create()
        {
            selectlist();
            return View();
        }

        [HttpPost]
        public IActionResult Create(CafeProduct cafeProduct)
        {
            _appDbContext.CafeProducts.Add(cafeProduct);
            _appDbContext.SaveChanges();
            TempData["create"] = "create sucess";
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Edit(int? ID)
        {
            var cafeProduct = _appDbContext.CafeProducts.Find(ID);
            selectlist();
            return View(cafeProduct);
        }

        [HttpPost]
        public IActionResult Edit(CafeProduct cafeProduct)
        {
            _appDbContext.CafeProducts.Update(cafeProduct);
            _appDbContext.SaveChanges();
            TempData["Edit"] = "edit done";
            return RedirectToAction("Index");
        }




        public ViewResult Delete(int ID) 
        {
            CafeProduct C1=(from caf in _appDbContext.CafeProducts
                            where caf.ID == ID
                            select caf).FirstOrDefault();
            _appDbContext.CafeProducts.Remove(C1);
            _appDbContext.SaveChanges();
            TempData["Delete"] = "Delete done";

            List<CafeProduct> lista = _appDbContext.CafeProducts.Include(c => c.Size).ToList();

            return View("Index",lista);

        }

        public void selectlist(int selectid=0)
        {
            List<Size> sizes=_appDbContext.Sizes.ToList();

            SelectList selectListItems = new SelectList(sizes, "Id", "Name",selectid);
            ViewBag.selecto = selectListItems;
        }

    }
}

Cafe/Views/CafeProduct/Create.cshtml
@model CafeProduct
@{
    ViewData["Title"] = "Create";
}




<form method="post" style="margin-top:150px;">
   
    <div class="border p-3 mt-4" >
        <div class="row pb-3">
            <h1 class="text-primary">add new Item</h1>
            <hr />
        </div>

        <div asp-validation-summary="All"></div> @* عشان يطلع رساله غلط *@
        <div class="mb-3">
            <label asp-for="Name" >Name</label>
            <input class="form-control" asp-for="Name"/>
            <span asp-validation-for="Name" class="text-danger"></span>@* عشان يطلع رساله غلط *@
 
        </div>

        <div class="mb-3">
            <label asp-for="Description">Description</label>
            <input class="form-control" asp-for="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>@* عشان يطلع رساله غلط *@
        </div>


    

        <div class="mb-3">
            <select class="form-control" asp-for="SizeId" asp-items="@ViewBag.selecto"></select>
        </div>

       

        <button type="submit" class="btn btn-primary" style="width:150px">save</button>

        <a class="btn btn-warning" style="width:150px" asp-action="Index" asp-controller="CafeProduct">Back</a>
    </div>
</form>



    @*  هيك التحقق من جهه العميل ما بعمل خمل ع database server *@
        @section Scripts{
    <partial name="_ValidationScriptsPartial.cshtml"></partial>
        }

Cafe/Views/CafeProduct/Edit.cshtml
@model CafeProduct
@{
    ViewData["Title"] = "Create";
}




<form method="post" style="margin-top:150px;">

    <div class="border p-3 mt-4">
        <div class="row pb-3">
            <h1 class="text-primary">Edit new Item</h1>
            <hr />
        </div>

        <div asp-validation-summary="All"></div> @* عشان يطلع رساله غلط *@
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input class="form-control" asp-for="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>@* عشان يطلع رساله غلط *@

        </div>

        <div class="mb-3">
            <label asp-for="Description">Description</label>
            <input class="form-control" asp-for="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>@* عشان يطلع رساله غلط *@
        </div>




        <div class="mb-3">
            <select class="form-control" asp-for="SizeId" asp-items="@ViewBag.selecto"></select>
        </div>



        <button type="submit" class="btn btn-primary" style="width:150px">save</button>

        <a class="btn btn-warning" style="width:150px" asp-action="Index" asp-controller="CafeProduct">Back</a>
    </div>
</form>



@*  هيك التحقق من جهه العميل ما بعمل خمل ع database server *@
@section Scripts {
    <partial name="_ValidationScriptsPartial.cshtml"></partial>
}

Cafe/Views/CafeProduct/Index.cshtml
@model List<CafeProduct>


<h1 style="margin-top:150px;" class="text-primary"> Cafe Product</h1>

<partial name="Massege" />

<div>
    <a asp-controller="CafeProduct" asp-action="Create" asp-route-ID="" class="btn btn-success">Create</a>   

</div>


<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Product Name</th>
            <th scope="col">Description</th>
            <th scope="col">Size</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
      
    
        @foreach(CafeProduct i in Model)
        {
            <tr class="table-primary">
                <td>@i.Name</td>
                <td>@i.Description</td>
                <td>@i.Size.Name</td>


                    <td>

                    <a asp-controller="CafeProduct" asp-action="Edit" asp-route-ID="@i.ID" class="btn btn-success"><i class="bi bi-pen"></i></a>   &nbsp;
                    <a asp-controller="CafeProduct" asp-action="Delete" asp-route-ID="@i.ID" class="btn btn-danger"><i class="bi bi-trash"></i></a>
                    </td>

            </tr>
        }

        
      
      
     
    
    </tbody>
</table>



               @*  cardprice *@

<div id="header">
    <h1>La Saveur</h1>
    <p>The Traditional Fench Taste</p>
</div>
<div id="container" class="container">
    <div class="card">
        <div class="card-image">
            <img src="https://images.unsplash.com/photo-1604135307399-86c6ce0aba8e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1374&q=80">
        </div>
        <div class="card-text">
            <p class="card-meal-type">Breakfast/Eggs</p>
            <h2 class="card-title">Délicieux Bénédicte</h2>
            <p class="card-body">Eggs Benedict with hollandaise sauce, crispy bacon and an assortment of garden herbs.</p>
        </div>
        <div class="card-price">$56</div>
    </div>
    <div class="card">
        <div class="card-image">
            <img src="https://images.unsplash.com/photo-1551782450-17144efb9c50?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1769&q=80">
        </div>
        <div class="card-text">
            <p class="card-meal-type">Lunch/Meat</p>
            <h2 class="card-title">Du bœuf Burger</h2>
            <p class="card-body">A beef burger with wholewheat patty, juicy lettuce and a side of gluten free fries</p>
        </div>
        <div class="card-price">$39</div>
    </div>
    <div class="card">
        <div class="card-image">
            <img src="https://images.pexels.com/photos/2113556/pexels-photo-2113556.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1">
        </div>
        <div class="card-text">
            <p class="card-meal-type">Sweets</p>
            <h2 class="card-title">Soupe à l’oignon</h2>
            <p class="card-body">The traditional French soup made with onions and beef with a dollop of garlic and saffaron mayonise.</p>
        </div>
        <div class="card-price">$69</div>
    </div>
    <div class="card">
        <div class="card-image">
            <img src="https://images.pexels.com/photos/2662875/pexels-photo-2662875.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1">
        </div>
        <div class="card-text">
            <p class="card-meal-type">BreakFast</p>
            <h2 class="card-title">Coq au Vin</h2>
            <p class="card-body">Chickens doused in wine, mushrooms, pork, onions and garlic.</p>
        </div>
        <div class="card-price">$104</div>
    </div>

</div>

<style>
    body {
        background: url(https://images.unsplash.com/photo-1495195129352-aeb325a55b65?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1776&q=80);

    }

    #header {
        margin: 20px;
    }

        #header > h1 {
            text-align: center;
            font-size: 3rem;
        }

        #header > p {
            text-align: center;
            font-size: 1.5rem;
            font-style: italic;
        }

    #container {
        width: 100vw;
        display: flex;
        justify-content: space-around;
        flex-wrap: wrap;
        padding: 40px 20px;
    }

    .card {
        display: flex;
        flex-direction: column;
        width: 400px;
        margin-bottom: 60px;
    }

        .card > div {
            box-shadow: 0 15px 20px 0 rgba(0,0,0,0.5);
        }

    .card-image {
        width: 400px;
        height: 250px;
    }

        .card-image > img {
            width: 100%;
            height: 100%;
            object-fit: cover;
            object-position: bottom;
        }

    .card-text {
        margin: -30px auto;
        margin-bottom: -50px;
        height: 300px;
        width: 300px;
        background-color: #1D1C20;
        color: #fff;
        padding: 20px;
    }

    .card-meal-type {
        font-style: italic;
    }

    .card-title {
        font-size: 2.2rem;
        margin-bottom: 20px;
        margin-top: 5px;
    }

    .card-body {
        font-size: 1.25rem;
    }

    .card-price {
        width: 100px;
        height: 100px;
        background-color: #970C0A;
        color: #fff;
        margin-left: auto;
        font-size: 2rem;
        display: flex;
        justify-content: center;
        align-items: center;
    }

</style>
               @*  cardprice *@